config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  #resources :comments #(replaced by mount, below)
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolios/angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: "portfolios#show", as: 'portfolio_show'
  
  #get 'pages/home'
  #get 'pages/about'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'pages/test', to: 'pages#test'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, 
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }
  
  validates_presence_of :title, :body
  
  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader
  
  def self.angular
    where(subtitle: "Angular")
  end
  
  def self.by_position
    order("position ASC")
  end
  
  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
  
  def index
    @portfolio_items = Portfolio.by_position
  end
  
  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    
    render nothing: true
  end
  
  def angular
    @portfolio_items = Portfolio.angular
  end
  
  def new 
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end
  
  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    #Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name]))

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def edit 
    @portfolio_item = Portfolio.find(params[:id])
  end
  
  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  
  def show
    @portfolio_item = Portfolio.find(params[:id])
  end
  
  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Item was successfully destroyed.' }
    end
  end
  
  private
  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body, 
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                      )
  end
  
  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
  
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end
  
  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height:'350', width: '200')
    elsif type == 'main'
      image_generator(height:'600', width: '400')
    end
  end
  
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end
  
  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)
    
    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }
    
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
  
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= f.file_field :main_image, style: 'display:none;' %>
        </label>
      </div>
      
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none;' %>
        </label>
      </div>
    </div>
    
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  
  
    <hr>
    
    <div class="col-md-12">
      <h4>Technologies Used</h4>
      <div>
        <%= f.fields_for :technologies do |technology_form|%>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>
        
        <div>
          <%= link_to_add_association 'Add Technology', f, :technologies %>
        </div>
      </div>
      
    </div>
  </div>
      
  <div class="form-group">
    <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
  </div>

  
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card" data-id="<%= portfolio_item.id %>">
    <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%' %>
    <p class="card-text">
      <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></span>
      <%= portfolio_item.subtitle %>
    </p>
  </div>
</div>




<!--
<p><%= portfolio_item.body %></p>

<br>
<%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin)%>
<%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)%>
-->

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin)%>

<hr>

<% @portfolio_items.each do |item| %>
  <h2><%= link_to item.title, portfolio_show_path(item.id) %></h2>
  <p><%= item.subtitle %></p>
  <p><%= item.body %></p>
  <%= image_tag item.thumb_image if !item.thumb_image.nil?%><br>
  <%= link_to "Edit", edit_portfolio_path(item.id) if logged_in?(:site_admin)%>
  <%= link_to 'Destroy', portfolio_path(item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)%>
<% end %> 

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio Item</h1>
  <%= render 'form', portfolio: @portfolio_item %>
  
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted portfolio-index-container">
  
  <div class="container ">
    <%= source_helper("alert alert-success") %>
    
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
      
      
    </div>
    
  </div>
</div>




<!--
<a href="portfolios/new">Create New Item</a> <br>
<p>Portfolio Path (relative path):<br>
  <%= new_portfolio_path %>
</p>
<p>Portfolio URL:<br>
  <%= new_portfolio_url %>
</p>
-->

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio Item</h1>
  
  <%= render 'form', portfolio: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    
    <div class="col-md-7">
      <p><%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %></p>
    </div>
    
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= markdown @portfolio_item.body %></p>
      <hr>
      <% if !(@portfolio_item.technologies.count == 0) %>
        <h4>Technologies Used</h4>
        <% @portfolio_item.technologies.each do |t| %>
          <p><%= t.name %></p>
        <% end %>
      <% end %>  
      
      <% if logged_in?(:site_admin) %>
      <div>
        <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: 'btn btn-success' %>
      </div>
      <% end %>
      
    </div>
    
  </div>
</div>

<!--
<p>Raw Code: <%= @portfolio_item.inspect %></p>
<%= params.inspect %>
<%= session.inspect %> 
-->